# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

products = Product.create([
{name: 'burger buns', category_id: 1,unit_id:6},
{name: 'english muffins', category_id: 1,unit_id:6},
{name: 'sourdough, round', category_id: 1,unit_id:6},
{name: 'sourdough, sliced', category_id: 1,unit_id:6},
{name: 'challah', category_id: 1,unit_id:6},
{name: 'lavosh', category_id: 1,unit_id:22},
{name: 'coffee, decaf', category_id: 2,unit_id:1},
{name: 'coffee, regular', category_id: 2,unit_id:1},
{name: 'equal packets', category_id: 2,unit_id:17},
{name: 'honey bears', category_id: 2,unit_id:6},
{name: 'sugar packets', category_id: 2,unit_id:17},
{name: 'sugar in the raw packets', category_id: 2,unit_id:17},
{name: 'tea, black iced', category_id: 2,unit_id:6},
{name: 'tea, breakfast', category_id: 2,unit_id:6},
{name: 'tea, earl grey', category_id: 2,unit_id:6},
{name: 'tea, chammomile', category_id: 2,unit_id:6},
{name: 'tea, green', category_id: 2,unit_id:6},
{name: 'tea, mint', category_id: 2,unit_id:6},
{name: 'butter, unsalted', category_id: 3,unit_id:1},
{name: 'cheese, american white', category_id: 3,unit_id:1},
{name: 'cheese, american yellow', category_id: 3,unit_id:1},
{name: 'cheese, blue crumbled', category_id: 3,unit_id:1},
{name: 'cheese, brie', category_id: 3,unit_id:1},
{name: 'cheese, burrata', category_id: 3,unit_id:1},
{name: 'cheese, cheddar sharp', category_id: 3,unit_id:1},
{name: 'cheese, cream', category_id: 3,unit_id:1},
{name: 'cheese, feta', category_id: 3,unit_id:1},
{name: 'cheese, fontina', category_id: 3,unit_id:1},
{name: 'cheese, curds', category_id: 3,unit_id:1},
{name: 'cheese, fontina', category_id: 3,unit_id:1},
{name: 'cheese, jack', category_id: 3,unit_id:1},
{name: 'cheese, macaroni', category_id: 3,unit_id:1},
{name: 'cheese, mozzarella shredded', category_id: 3,unit_id:1},
{name: 'cheese, pecorino', category_id: 3,unit_id:1},
{name: 'cheese, pepperjack', category_id: 3,unit_id:1},
{name: 'cheese, provolone', category_id: 3,unit_id:1},
{name: 'cheese, reginito', category_id: 3,unit_id:1},
{name: 'cheese, parmesan', category_id: 3,unit_id:1},
{name: 'cheese, swiss', category_id: 3,unit_id:1},
{name: 'cream, manufacturing', category_id: 3,unit_id:7},
{name: 'creme fraiche', category_id: 3,unit_id:24},
{name: 'eggs', category_id: 3,unit_id:18},
{name: 'ice cream, butter pecan', category_id: 3,unit_id:24},
{name: 'ice cream, coffee', category_id: 3,unit_id:24},
{name: 'ice cream, chocolate', category_id: 3,unit_id:24},
{name: 'ice cream, peanut butter', category_id: 3,unit_id:24},
{name: 'ice cream, strawberry', category_id: 3,unit_id:24},
{name: 'ice cream, vanilla bean', category_id: 3,unit_id:24},
{name: 'ice cream, straw sorbet', category_id: 3,unit_id:24},
{name: 'ice cream, orange sorbet', category_id: 3,unit_id:24},
{name: 'milk, buttermilk', category_id: 3,unit_id:7},
{name: 'sour cream', category_id: 3,unit_id:24},
{name: 'yogurt, lowfat', category_id: 3,unit_id:6},
{name: 'milk, homogonized', category_id: 3,unit_id:4},
{name: 'basa, frozen', category_id: 4,unit_id:1},
{name: 'crab meat', category_id: 4,unit_id:1},
{name: 'halibut', category_id: 4,unit_id:1},
{name: 'halibut', category_id: 4,unit_id:6},
{name: 'mussels, PEI', category_id: 4,unit_id:1},
{name: 'salmon', category_id: 4,unit_id:1},
{name: 'tuna', category_id: 4,unit_id:1},
{name: 'tuna', category_id: 4,unit_id:1},
{name: 'achiote paste', category_id: 5,unit_id:1},
{name: 'anchovies', category_id: 5,unit_id:16},
{name: 'baking powder', category_id: 5,unit_id:6},
{name: 'baking soda', category_id: 5,unit_id:6},
{name: 'baking soda', category_id: 5,unit_id:6},
{name: 'canola food release', category_id: 5,unit_id:6},
{name: 'beans, pinto', category_id: 5,unit_id:1},
{name: 'beans, black', category_id: 5,unit_id:1},
{name: 'beans, garbonzos', category_id: 5,unit_id:1},
{name: 'beans, kidney', category_id: 5,unit_id:1},
{name: 'capers', category_id: 5,unit_id:6},
{name: 'cereal, fruit loops', category_id: 5,unit_id:6},
{name: 'cereal, lucky charms', category_id: 5,unit_id:6},
{name: 'chile, chipotle', category_id: 5,unit_id:6},
{name: 'capers', category_id: 5,unit_id:6},
{name: 'chocolate, callabaut bittersweet', category_id: 5,unit_id:1},
{name: 'chocolate, unsweetened', category_id: 5,unit_id:1},
{name: 'chile, arbol', category_id: 5,unit_id:1},
{name: 'chile, ancho', category_id: 5,unit_id:1},
{name: 'chile, chipotle', category_id: 5,unit_id:6},
{name: 'chile, guajillo', category_id: 5,unit_id:1},
{name: 'chocolate, chips', category_id: 5,unit_id:1},
{name: 'chocolate, syrup', category_id: 5,unit_id:6},
{name: 'cocoa powder', category_id: 5,unit_id:1},
{name: 'coconut, shredded', category_id: 5,unit_id:1},
{name: 'coconut milk', category_id: 5,unit_id:6},
{name: 'corn, creamed', category_id: 5,unit_id:6},
{name: 'cornmeal', category_id: 5,unit_id:1},
{name: 'corn starch', category_id: 5,unit_id:1},
{name: 'cornichons', category_id: 5,unit_id:6},
{name: 'currants, dried', category_id: 5,unit_id:1},
{name: 'extract,vanilla', category_id: 5,unit_id:6},
{name: 'extract, vanilla', category_id: 5,unit_id:4},
{name: 'flour, high gluten', category_id: 5,unit_id:1},
{name: 'flour, AP', category_id: 5,unit_id:1},
{name: 'flour, cake', category_id: 5,unit_id:1},
{name: 'flour, rice', category_id: 5,unit_id:1},
{name: 'flour, semolina', category_id: 5,unit_id:1},
{name: 'flour, wheat', category_id: 5,unit_id:1},
{name: 'gramham', category_id: 5,unit_id:1},
{name: 'green peppercorn', category_id: 5,unit_id:6},
{name: 'grits', category_id: 5,unit_id:1},
{name: 'honey, bulk', category_id: 5,unit_id:6},
{name: 'horseradish', category_id: 5,unit_id:6},
{name: 'horseradish', category_id: 5,unit_id:6},
{name: 'jalapeno', category_id: 5,unit_id:6},
{name: 'ketchup, 10 can', category_id: 5,unit_id:6},
{name: 'ketchup, squeeze', category_id: 5,unit_id:6},
{name: 'lentils', category_id: 5,unit_id:1},
{name: 'mayonnise', category_id: 5,unit_id:6},
{name: 'mirin', category_id: 5,unit_id:6},
{name: 'mustard, dijon', category_id: 5,unit_id:6},
{name: 'mustard, whole grain', category_id: 5,unit_id:6},
{name: 'mustard, yellow', category_id: 5,unit_id:6},
{name: 'mustard, yellow small', category_id: 5,unit_id:6},
{name: 'nuts, almonds', category_id: 5,unit_id:1},
{name: 'nuts, hazelnuts', category_id: 5,unit_id:1},
{name: 'nuts, pistachio', category_id: 5,unit_id:1},
{name: 'nuts, peanuts', category_id: 5,unit_id:1},
{name: 'nuts, pine', category_id: 5,unit_id:1},
{name: 'nuts, walnuts', category_id: 5,unit_id:1},
{name: 'nutella', category_id: 5,unit_id:6},
{name: 'oil, canola fry', category_id: 5,unit_id:6},
{name: 'oil, extra virgin olive', category_id: 5,unit_id:6},
{name: 'oil, olive blend', category_id: 5,unit_id:4},
{name: 'oil, sesame', category_id: 5,unit_id:4},
{name: 'oil, truffle', category_id: 5,unit_id:6},
{name: 'olives, calamata', category_id: 5,unit_id:24},
{name: 'olives, calamata', category_id: 5,unit_id:24},
{name: 'olives, nicoise', category_id: 5,unit_id:24},
{name: 'panko', category_id: 5,unit_id:12},
{name: 'pasta, orrechiette de cecco', category_id: 5,unit_id:1},
{name: 'pancake mix', category_id: 5,unit_id:12},
{name: 'panko', category_id: 5,unit_id:12},
{name: 'pasta, elbow mac', category_id: 5,unit_id:1},
{name: 'pasta, spaghetti', category_id: 5,unit_id:1},
{name: 'paste, tahini', category_id: 5,unit_id:6},
{name: 'peanut butter', category_id: 5,unit_id:6},
{name: 'pickles, dill', category_id: 5,unit_id:24},
{name: 'rice, arborio', category_id: 5,unit_id:1},
{name: 'rice, white', category_id: 5,unit_id:1},
{name: 'popcorn', category_id: 5,unit_id:1},
{name: 'preserves, strawberry', category_id: 5,unit_id:6},
{name: 'quinoa', category_id: 5,unit_id:1},
{name: 'rice, calrose', category_id: 5,unit_id:1},
{name: 'salt, kosher', category_id: 5,unit_id:6},
{name: 'sauce, A-1', category_id: 5,unit_id:6},
{name: 'sauce, franks hot', category_id: 5,unit_id:4},
{name: 'sauce, tabasco', category_id: 5,unit_id:6},
{name: 'sauce, chalulah', category_id: 5,unit_id:6},
{name: 'sauce, franks hot', category_id: 5,unit_id:6},
{name: 'sauce, siracha', category_id: 5,unit_id:6},
{name: 'sauce, soy', category_id: 5,unit_id:4},
{name: 'sauce, soy', category_id: 5,unit_id:6},
{name: 'sauce, tabasco minis', category_id: 5,unit_id:6},
{name: 'sauce, tabasco large', category_id: 5,unit_id:6},
{name: 'sauce, worchestershire', category_id: 5,unit_id:6},
{name: 'shortening, solid', category_id: 5,unit_id:6},
{name: 'smoke, liquid', category_id: 5,unit_id:6},
{name: 'spice, allspice', category_id: 5,unit_id:21},
{name: 'spice, bay leaf', category_id: 5,unit_id:6},
{name: 'spice, black sesame seed', category_id: 5,unit_id:6},
{name: 'spice, cayenne pepper', category_id: 5,unit_id:6},
{name: 'spice, celery salt', category_id: 5,unit_id:6},
{name: 'spice, celery seed', category_id: 5,unit_id:6},
{name: 'spice, chili flakes', category_id: 5,unit_id:6},
{name: 'spice, chili flakes', category_id: 5,unit_id:6},
{name: 'spice, chili powder', category_id: 5,unit_id:6},
{name: 'spice, cinamon stick', category_id: 5,unit_id:6},
{name: 'spice, cinamon, ground', category_id: 5,unit_id:6},
{name: 'spice, cloves, whole', category_id: 5,unit_id:6},
{name: 'spice, coriander seed', category_id: 5,unit_id:6},
{name: 'spice, corriander seed', category_id: 5,unit_id:6},
{name: 'spice, cumin seed', category_id: 5,unit_id:6},
{name: 'spice, cumin', category_id: 5,unit_id:6},
{name: 'spice, curry powder', category_id: 5,unit_id:6},
{name: 'spice, mustard seed', category_id: 5,unit_id:6},
{name: 'spice, fennel seed', category_id: 5,unit_id:6},
{name: 'spice, garlic powder', category_id: 5,unit_id:6},
{name: 'spice, ginger, ground', category_id: 5,unit_id:6},
{name: 'spice, herbs de provence', category_id: 5,unit_id:1},
{name: 'spice, nutmeg, ground', category_id: 5,unit_id:6},
{name: 'spice, onion powder', category_id: 5,unit_id:6},
{name: 'spice, oregano dried', category_id: 5,unit_id:6},
{name: 'spice, old bay', category_id: 5,unit_id:6},
{name: 'spice, paprika', category_id: 5,unit_id:6},
{name: 'spice, pepper, cracked black', category_id: 5,unit_id:6},
{name: 'spice, pepper, white whole', category_id: 5,unit_id:6},
{name: 'spice, pickling spice', category_id: 5,unit_id:6},
{name: 'spice, star anise', category_id: 5,unit_id:1},
{name: 'sugar, brown', category_id: 5,unit_id:1},
{name: 'sugar, brown dark', category_id: 5,unit_id:6},
{name: 'sugar, granulated', category_id: 5,unit_id:1},
{name: 'sugar, powdered', category_id: 5,unit_id:6},
{name: 'syrup, maple', category_id: 5,unit_id:4},
{name: 'togo ketchup', category_id: 5,unit_id:17},
{name: 'togo mayo', category_id: 5,unit_id:17},
{name: 'togo mustard', category_id: 5,unit_id:17},
{name: 'tomato paste', category_id: 5,unit_id:16},
{name: 'tomato, whole peeled', category_id: 5,unit_id:16},
{name: 'tuna, albacore', category_id: 5,unit_id:6},
{name: 'vagelene', category_id: 5,unit_id:6},
{name: 'vinegar, balsamic', category_id: 5,unit_id:9},
{name: 'vinegar, cider', category_id: 5,unit_id:6},
{name: 'vinegar, malt', category_id: 5,unit_id:6},
{name: 'vinegar, red wine', category_id: 5,unit_id:4},
{name: 'vinegar, rice', category_id: 5,unit_id:4},
{name: 'vinegar, sherry', category_id: 5,unit_id:6},
{name: 'vinegar, white distilled', category_id: 5,unit_id:6},
{name: 'vinegar, white wine', category_id: 5,unit_id:4},
{name: 'wasabi powder', category_id: 5,unit_id:6},
{name: 'wine, red', category_id: 5,unit_id:5},
{name: 'wine, white', category_id: 5,unit_id:5},
{name: 'wine, white box', category_id: 5,unit_id:6},
{name: 'wine, red box', category_id: 5,unit_id:6},
{name: 'tortillas', category_id: 5,unit_id:12},
{name: 'yeast, fresh', category_id: 5,unit_id:6},
{name: 'rum', category_id: 5,unit_id:6},
{name: 'syrup, simple', category_id: 5,unit_id:6},
{name: 'whiskey', category_id: 5,unit_id:5},
{name: 'worcestershire', category_id: 5,unit_id:5},
{name: 'olives', category_id: 5,unit_id:6},
{name: 'juice, apple', category_id: 5,unit_id:4},
{name: 'bev naps', category_id: 5,unit_id:22},
{name: 'torani', category_id: 5,unit_id:5},
{name: 'juice, grapefruit', category_id: 5,unit_id:7},
{name: 'grapes, green', category_id: 5,unit_id:1},
{name: 'bacon, canadian', category_id: 6,unit_id:1},
{name: 'bacon, sliced', category_id: 6,unit_id:1},
{name: 'beef bones', category_id: 6,unit_id:1},
{name: 'beef cheeks', category_id: 6,unit_id:1},
{name: 'brisket', category_id: 6,unit_id:1},
{name: 'chicken, 2.5# wog', category_id: 6,unit_id:1},
{name: 'chicken, random breasts', category_id: 6,unit_id:1},
{name: 'chicken tenders', category_id: 6,unit_id:1},
{name: 'coppa, hot', category_id: 6,unit_id:1},
{name: 'chicken wings', category_id: 6,unit_id:1},
{name: 'coppa, hot', category_id: 6,unit_id:1},
{name: 'corned beef', category_id: 6,unit_id:1},
{name: 'bacon, smoked', category_id: 6,unit_id:1},
{name: 'chicken, WOGS', category_id: 6,unit_id:1},
{name: 'chicken wings', category_id: 6,unit_id:1},
{name: 'chicken, ground', category_id: 6,unit_id:1},
{name: 'chicken, randoms', category_id: 6,unit_id:1},
{name: 'turkey, ground', category_id: 6,unit_id:1},
{name: 'pastrami', category_id: 6,unit_id:1},
{name: 'lamb, shanks', category_id: 6,unit_id:1},
{name: 'spanish chorizo', category_id: 6,unit_id:1},
{name: 'pork, loin', category_id: 6,unit_id:1},
{name: 'pork butt', category_id: 6,unit_id:1},
{name: 'ham, black forrest', category_id: 6,unit_id:1},
{name: 'turkey, ground', category_id: 6,unit_id:1},
{name: 'pork, belly', category_id: 6,unit_id:1},
{name: 'pork, shoulders', category_id: 6,unit_id:1},
{name: 'prosciutto', category_id: 6,unit_id:1},
{name: 'sausage, chorizo fresh', category_id: 6,unit_id:1},
{name: 'sausage, chicken apple', category_id: 6,unit_id:1},
{name: 'sausage, chorizo', category_id: 6,unit_id:1},
{name: 'sausage, italian', category_id: 6,unit_id:1},
{name: 'sausage, kielbasa', category_id: 6,unit_id:1},
{name: 'sausage, chicken apple', category_id: 6,unit_id:1},
{name: 'sausage, pepperoni', category_id: 6,unit_id:1},
{name: 'steak, bistro filet', category_id: 6,unit_id:1},
{name: 'steak, new york', category_id: 6,unit_id:1},
{name: 'steak, skirt', category_id: 6,unit_id:1},
{name: 'steak, chuck roll', category_id: 6,unit_id:1},
{name: 'steak, brisket', category_id: 6,unit_id:1},
{name: 'steak, flat iron', category_id: 6,unit_id:1},
{name: 'steak, short ribs', category_id: 6,unit_id:1},
{name: 'asparagus', category_id: 8,unit_id:6},
{name: 'avocados', category_id: 8,unit_id:6},
{name: 'brussels sprouts', category_id: 8,unit_id:1},
{name: 'cabbage, green', category_id: 8,unit_id:6},
{name: 'carrots', category_id: 8,unit_id:1},
{name: 'carrots, baby', category_id: 8,unit_id:1},
{name: 'celery', category_id: 8,unit_id:6},
{name: 'chili, ancho', category_id: 8,unit_id:1},
{name: 'corn, sweet', category_id: 8,unit_id:6},
{name: 'cucumbers, regular', category_id: 8,unit_id:17},
{name: 'cucumbers, hot house', category_id: 8,unit_id:6},
{name: 'fennel', category_id: 8,unit_id:6},
{name: 'fruit, apples, granny smith', category_id: 8,unit_id:17},
{name: 'fruit, bananas', category_id: 8,unit_id:1},
{name: 'fruit, blackberry fro', category_id: 8,unit_id:6},
{name: 'fruit, strawberry frozen', category_id: 8,unit_id:1},
{name: 'fruit, cranberries frozen', category_id: 8,unit_id:1},
{name: 'fruit, pears', category_id: 8,unit_id:1},
{name: 'fruit, strawberries', category_id: 8,unit_id:25},
{name: 'garlic, peeled', category_id: 8,unit_id:1},
{name: 'ginger', category_id: 8,unit_id:1},
{name: 'grits', category_id: 8,unit_id:1},
{name: 'herb, basil', category_id: 8,unit_id:26},
{name: 'herb, chervil', category_id: 8,unit_id:2},
{name: 'herb, chives', category_id: 8,unit_id:1},
{name: 'herb, cilantro', category_id: 8,unit_id:26},
{name: 'herb, dill', category_id: 8,unit_id:1},
{name: 'herb, kaiware', category_id: 8,unit_id:6},
{name: 'herb, micro cilantro', category_id: 8,unit_id:6},
{name: 'herb, oregano', category_id: 8,unit_id:1},
{name: 'herb, parsley', category_id: 8,unit_id:26},
{name: 'herb, rosemary', category_id: 8,unit_id:26},
{name: 'herb, sage', category_id: 8,unit_id:26},
{name: 'herb, thyme', category_id: 8,unit_id:1},
{name: 'juice, lemon', category_id: 8,unit_id:4},
{name: 'juice, lime', category_id: 8,unit_id:6},
{name: 'lettuce, arugula', category_id: 8,unit_id:1},
{name: 'lettuce, iceberg', category_id: 8,unit_id:6},
{name: 'lettuce, mixed greens', category_id: 8,unit_id:17},
{name: 'lettuce, romaine hearts', category_id: 8,unit_id:6},
{name: 'mushroom, crimini', category_id: 8,unit_id:1},
{name: 'onion, green', category_id: 8,unit_id:26},
{name: 'onions, red', category_id: 8,unit_id:1},
{name: 'onions, yellow', category_id: 8,unit_id:1},
{name: 'peppers, green bell', category_id: 8,unit_id:1},
{name: 'pepper, red bell', category_id: 8,unit_id:1},
{name: 'peppers, jalapeno', category_id: 8,unit_id:1},
{name: 'peppers, red bells', category_id: 8,unit_id:1},
{name: 'peppers, serrano', category_id: 8,unit_id:1},
{name: 'peppers, yellow bell', category_id: 8,unit_id:1},
{name: 'potato, russets', category_id: 8,unit_id:1},
{name: 'potato, kennebeck', category_id: 8,unit_id:17},
{name: 'potato, red B', category_id: 8,unit_id:1},
{name: 'potato, sweet', category_id: 8,unit_id:1},
{name: 'radicchio, red', category_id: 8,unit_id:6},
{name: 'radish, red', category_id: 8,unit_id:26},
{name: 'shallots, peeled', category_id: 8,unit_id:21},
{name: 'squash, butternut', category_id: 8,unit_id:1},
{name: 'tomato 5x6', category_id: 8,unit_id:17},
{name: 'tomato, heirloom', category_id: 8,unit_id:17},
{name: 'tortillas, corn', category_id: 8,unit_id:22},
{name: 'tortillas, white', category_id: 8,unit_id:22},
{name: 'wonton wraps', category_id: 8,unit_id:22},
{name: 'Absolut', category_id: 10,unit_id:5},
{name: 'Absolut acai', category_id: 10,unit_id:5},
{name: 'Absolut citron', category_id: 10,unit_id:5},
{name: 'Absolut Mandarin', category_id: 10,unit_id:5},
{name: 'absolut orient apple', category_id: 10,unit_id:5},
{name: 'Absolut Vanilla', category_id: 10,unit_id:5},
{name: 'Absolut pear', category_id: 10,unit_id:5},
{name: 'Burnetts Citron', category_id: 10,unit_id:5},
{name: 'Belvedere', category_id: 10,unit_id:5},
{name: 'Grey Goose', category_id: 10,unit_id:5},
{name: 'Ketel One', category_id: 10,unit_id:5},
{name: 'Ketel One Citron', category_id: 10,unit_id:5},
{name: 'Pearl Pomegranite', category_id: 10,unit_id:5},
{name: 'Ciroc', category_id: 10,unit_id:5},
{name: 'Stoli', category_id: 10,unit_id:5},
{name: 'Ultimat Vodka', category_id: 10,unit_id:5},
{name: 'Nikolai', category_id: 10,unit_id:5},
{name: 'Beefeater', category_id: 11,unit_id:5},
{name: 'Bombay', category_id: 11,unit_id:5},
{name: 'Bombay Sapphire', category_id: 11,unit_id:5},
{name: 'Hendricks', category_id: 11,unit_id:5},
{name: 'Burnetts (well)', category_id: 11,unit_id:5},
{name: 'Tanqueray', category_id: 11,unit_id:5},
{name: 'Juniper', category_id: 11,unit_id:5},
{name: 'Bacardi Light', category_id: 12,unit_id:5},
{name: 'Bacardi Cherry', category_id: 12,unit_id:5},
{name: 'Bacardi limon', category_id: 12,unit_id:5},
{name: 'Bacardi 151', category_id: 12,unit_id:5},
{name: 'Ron Rio (well)', category_id: 12,unit_id:5},
{name: '51 Cachaca', category_id: 12,unit_id:5},
{name: 'Captain Morgan', category_id: 12,unit_id:5},
{name: 'Goslings', category_id: 12,unit_id:5},
{name: 'Malibu', category_id: 12,unit_id:5},
{name: 'Meyers', category_id: 12,unit_id:5},
{name: 'Whalers Dark Rum', category_id: 12,unit_id:5},
{name: 'Don Julio Anejo', category_id: 13,unit_id:5},
{name: 'Don Julio Blanco', category_id: 13,unit_id:5},
{name: 'Patron Anejo', category_id: 13,unit_id:5},
{name: 'Patron Silver', category_id: 13,unit_id:5},
{name: 'Patron Reposado', category_id: 13,unit_id:5},
{name: 'Sauza Hornitos', category_id: 13,unit_id:5},
{name: 'Sauza Gold', category_id: 13,unit_id:5},
{name: 'Casadores Anejo', category_id: 13,unit_id:5},
{name: 'Casadores Blanco', category_id: 13,unit_id:5},
{name: 'Casadores Reposado', category_id: 13,unit_id:5},
{name: 'Torada Silver', category_id: 13,unit_id:5},
{name: 'Tres Reyes', category_id: 13,unit_id:5},
{name: 'Bushmills', category_id: 14,unit_id:5},
{name: 'Canadian Club', category_id: 14,unit_id:5},
{name: 'Crown Royal', category_id: 14,unit_id:5},
{name: 'Jameson', category_id: 14,unit_id:5},
{name: 'Kilbeggen', category_id: 14,unit_id:5},
{name: 'Seagrams 7', category_id: 14,unit_id:5},
{name: 'Evan Williams', category_id: 14,unit_id:5},
{name: 'Redbreast', category_id: 14,unit_id:5},
{name: 'Old Overholt', category_id: 14,unit_id:5},
{name: 'Powers', category_id: 14,unit_id:5},
{name: 'Seagrams VO', category_id: 14,unit_id:5},
{name: 'Basil Hayden', category_id: 15,unit_id:5},
{name: 'Bookers', category_id: 15,unit_id:5},
{name: 'Jack Daniels', category_id: 15,unit_id:5},
{name: 'Gentleman Jack', category_id: 15,unit_id:5},
{name: 'Jim Beam', category_id: 15,unit_id:5},
{name: 'Jim beam Red stag', category_id: 15,unit_id:5},
{name: 'Knob Creek', category_id: 15,unit_id:5},
{name: 'Makers Mark', category_id: 15,unit_id:5},
{name: 'Southern Comfort', category_id: 15,unit_id:5},
{name: 'Wild Turkey 101', category_id: 15,unit_id:5},
{name: 'Woodford Reserve', category_id: 15,unit_id:5},
{name: 'Chivas', category_id: 16,unit_id:5},
{name: 'Dewars', category_id: 16,unit_id:5},
{name: 'J&B', category_id: 16,unit_id:5},
{name: 'Johnny Walker Black', category_id: 16,unit_id:5},
{name: 'Glenfiddich', category_id: 16,unit_id:5},
{name: 'Glenlivit', category_id: 16,unit_id:5},
{name: 'Lagavulin', category_id: 16,unit_id:5},
{name: 'Macallan 12', category_id: 16,unit_id:5},
{name: 'Oban 14', category_id: 16,unit_id:5},
{name: 'House of Stuart (well)', category_id: 16,unit_id:5},
{name: 'Amaretto di Soronno', category_id: 17,unit_id:5},
{name: 'Dekeyper Amaretto', category_id: 17,unit_id:5},
{name: 'Absinthe', category_id: 17,unit_id:5},
{name: 'Apple Pucker', category_id: 17,unit_id:5},
{name: 'Baileys', category_id: 17,unit_id:5},
{name: 'Benedictine', category_id: 17,unit_id:5},
{name: 'Campari', category_id: 17,unit_id:5},
{name: 'Canton', category_id: 17,unit_id:5},
{name: 'Cointreau', category_id: 17,unit_id:5},
{name: 'Chambord', category_id: 17,unit_id:5},
{name: 'Chartreuse Yellow', category_id: 17,unit_id:5},
{name: 'Chartreuse Green', category_id: 17,unit_id:5},
{name: 'Creme de Cacao', category_id: 17,unit_id:5},
{name: 'Creme de Menthe', category_id: 17,unit_id:5},
{name: 'Drambuie', category_id: 17,unit_id:5},
{name: 'Vermouth-Dry', category_id: 17,unit_id:5},
{name: 'Vermouth-Sweet', category_id: 17,unit_id:5},
{name: 'Frangelico', category_id: 17,unit_id:5},
{name: 'Galliano', category_id: 17,unit_id:5},
{name: 'Grand Marnier', category_id: 17,unit_id:5},
{name: 'Hypnotiq', category_id: 17,unit_id:5},
{name: 'Irish Manor Cream', category_id: 17,unit_id:5},
{name: 'Jagermeister', category_id: 17,unit_id:5},
{name: 'Kahlua', category_id: 17,unit_id:5},
{name: 'Midori', category_id: 17,unit_id:5},
{name: 'Patron Cafe XO', category_id: 17,unit_id:5},
{name: 'Patron Citronge', category_id: 17,unit_id:5},
{name: 'Peach Brandy', category_id: 17,unit_id:5},
{name: 'Roses Grenadine', category_id: 17,unit_id:5},
{name: 'Sambuca', category_id: 17,unit_id:5},
{name: 'St Germaine', category_id: 17,unit_id:5},
{name: 'Triple Sec', category_id: 17,unit_id:5},
{name: 'Veev', category_id: 17,unit_id:5},
{name: 'Fever Tree Ginger Beer', category_id: 17,unit_id:5},
{name: 'Root Beer', category_id: 17,unit_id:5},
{name: 'Courvoisier VSOP', category_id: 18,unit_id:5},
{name: 'Hennessy VS', category_id: 18,unit_id:5},
{name: 'Korbel Brandy', category_id: 18,unit_id:5},
{name: 'Remy Martin VSOP', category_id: 18,unit_id:5},
{name: 'Remy Martin 1738', category_id: 18,unit_id:5},
{name: 'Shiner Bock', category_id: 19,unit_id:5},
{name: 'Corona', category_id: 19,unit_id:5},
{name: 'Red Stripe', category_id: 19,unit_id:5},
{name: 'Miller Lite', category_id: 19,unit_id:5},
{name: 'Tecate', category_id: 19,unit_id:5},
{name: 'Pyramid Hefeweizen', category_id: 19,unit_id:5},
{name: 'Stone IPA', category_id: 19,unit_id:5},
{name: 'Lagunitas Pilsner', category_id: 19,unit_id:5},
{name: 'Fat Tire', category_id: 19,unit_id:5},
{name: 'St. Pauli Girl', category_id: 19,unit_id:5},
{name: '1/2 BBL Amstel', category_id: 20,unit_id:27},
{name: '1/2 BBL Blue Moon', category_id: 20,unit_id:27},
{name: '1/2 BBL Arrogant Bastard', category_id: 20,unit_id:27},
{name: '1/2 BBL Newcastle', category_id: 20,unit_id:27},
{name: '1/2 BBL Guinness', category_id: 20,unit_id:27},
{name: '1/2 BBL Strongbow Cider', category_id: 20,unit_id:27},
{name: '5 gal Chimay White', category_id: 20,unit_id:11},
{name: '5 gal Delirium Tremens', category_id: 20,unit_id:11},
{name: '1/2 BBL GF Hop Head Red', category_id: 20,unit_id:27},
{name: '5 gal Doggie Style', category_id: 20,unit_id:11},
{name: 'Empty Kegs', category_id: 20,unit_id:6},
{name: 'Domaine St Michele ', category_id: 21,unit_id:5},
{name: 'Wycliff Brut ', category_id: 21,unit_id:5},
{name: 'Coppola Pinot Grigio', category_id: 21,unit_id:5},
{name: 'Firestone Sauv Blanc', category_id: 21,unit_id:5},
{name: 'Kenwood Pinot Noir', category_id: 21,unit_id:5},
{name: 'Avalon Cabernet', category_id: 21,unit_id:5},
{name: 'Ruffino Chianti', category_id: 21,unit_id:5},
{name: 'Gladiator Merlot', category_id: 21,unit_id:5},
{name: 'Valley of the Moon PB', category_id: 21,unit_id:5},
{name: 'Sebastiani Merlot', category_id: 21,unit_id:5},
{name: 'Bogle Riesling', category_id: 21,unit_id:5},
{name: 'Bogle Petit Syrah', category_id: 21,unit_id:5},
{name: 'Folie Menage A Trois', category_id: 21,unit_id:5},
{name: 'Gnarly Head Zin', category_id: 21,unit_id:5},
{name: 'Joel Gott Chardonnay', category_id: 21,unit_id:5},
{name: 'Kris Pinot Grigio', category_id: 21,unit_id:5},
{name: 'Main Star Chardonnay', category_id: 21,unit_id:5},
{name: 'Tishbi SB - Kosher', category_id: 21,unit_id:5},
{name: 'Fortant Cab - Kosher', category_id: 21,unit_id:5},
{name: 'Kitchen Wine (white)', category_id: 21,unit_id:5},
{name: 'Kitchen Wine (red)', category_id: 21,unit_id:5},
{name: 'Sparkling', category_id: 22,unit_id:5},
{name: 'Flat', category_id: 22,unit_id:5},
{name: 'Beverage Napkins', category_id: 22,unit_id:17},
{name: 'Cocktail Straws', category_id: 22,unit_id:17},
{name: 'Tall Straws', category_id: 22,unit_id:14},
{name: 'Swords', category_id: 22,unit_id:14},
{name: 'Bitters', category_id: 22,unit_id:5},
{name: 'Worcestershire', category_id: 22,unit_id:5},
{name: 'Cocktail Onions', category_id: 22,unit_id:21},
{name: 'Olives', category_id: 22,unit_id:21},
{name: 'Cherries', category_id: 22,unit_id:21},
{name: 'Cranberry Juice', category_id: 22,unit_id:5},
{name: 'Orange Juice', category_id: 22,unit_id:4},
{name: 'Lime Juice', category_id: 22,unit_id:4},
{name: 'Lemon Juice', category_id: 22,unit_id:4},
{name: 'Pineapple Juice', category_id: 22,unit_id:16},
{name: 'Grapefruit Juice', category_id: 22,unit_id:28},
{name: 'Pomegranite Juice', category_id: 22,unit_id:28},
{name: 'Tomato Juice', category_id: 22,unit_id:16},
{name: 'Strawberry Puree', category_id: 22,unit_id:5},
{name: 'Rasberry Puree', category_id: 22,unit_id:5},
{name: 'Peach Puree', category_id: 22,unit_id:5},
{name: 'Pineapple Puree', category_id: 22,unit_id:5},
{name: 'Blackberry Puree', category_id: 22,unit_id:5},
{name: 'Mango Puree', category_id: 22,unit_id:5},
{name: 'Simple Syrup', category_id: 22,unit_id:4},
{name: 'Glass Coke', category_id: 22,unit_id:5},
{name: '20 oz Coke', category_id: 22,unit_id:5},
{name: '20 oz Diet Coke', category_id: 22,unit_id:5},
{name: '20 oz Sprite', category_id: 22,unit_id:5},
{name: 'Coke', category_id: 22,unit_id:14},
{name: 'Diet Coke', category_id: 22,unit_id:14},
{name: 'Tonic', category_id: 22,unit_id:14},
{name: 'Sprite', category_id: 22,unit_id:14},
{name: 'Gingerale', category_id: 22,unit_id:14},
{name: 'Nitrogen', category_id: 22,unit_id:6},
{name: 'CO2', category_id: 22,unit_id:6}
])